config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :dashboard, only: [:show]
  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end
  resources :lessons, only: [:show]
  namespace :instructor do
    resources :lessons, only: [:update]
    resources :sections, only: [] do
      resources :lessons, only: [:create]
    end
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create]
    end
  end
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user
  has_many :sections
  has_many :enrollments

  validates :title, presence: true
  validates :description, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}

  def free?
    cost.zero?
  end 

  def premium?
    ! free?
  end
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course
  belongs_to :user
end 

app/models/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!

  def create
      current_user.enrollments.create(course: current_course)
      redirect_to course_path(current_course)
  end

  private

  def current_course
    @current_course ||= Course.find(params[:course_id])
  end
end
 

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :section
  mount_uploader :video, VideoUploader

  include RankedModel
  ranks :row_order, with_same: :section_id

  def next_lesson
    lesson = section.lessons.where("row_order > ?", self.row_order).rank(:row_order).first
    if lesson.blank? && section.next_section
      return section.next_section.lessons.rank(:row_order).first
    end    
    return lesson
  end
end 

app/models/section.rb
class Section < ApplicationRecord
 belongs_to :course
 has_many :lessons

   include RankedModel
  ranks :row_order, with_same: :course_id

  def next_section
    section = course.sections.where("row_order > ?", self.row_order).rank(:row_order).first
    return section
  end
 end 

app/models/user.rb
class User < ApplicationRecord
  has_many :courses
  has_many :enrollments
  has_many :enrolled_courses, through: :enrollments, source: :course


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    def enrolled_in?(course)
    return enrolled_courses.include?(course)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!


  def show
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!

  def create
    if current_course.premium?
    current_user.enrollments.create(course: current_course)


    # Amount in cents
    @amount = (current_course.cost * 100).to_i

    customer = Stripe::Customer.create(
      email: params[:stripeEmail],
      source: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @amount,
      description: 'Flixter Premo Content',
      currency: 'usd'
    )
  end

  current_user.enrollments.create(course: current_course)
  redirect_to course_path(current_course)
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
    redirect_to root_path
  end

  private

  def current_course
    @current_course ||= Course.find(params[:course_id])
  end
end 

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only: [:show]


  def new
    @course = Course.new
  end

    def create
    @course = current_user.courses.create(course_params)
    redirect_to instructor_course_path(@course)
  end

    def show
    @course = Course.find(params[:id])
    if @course.valid?
      redirect_to instructor_course_path(@course)
    else 
      render :new, status: :unprocessable_entity
    end
    end

    def index
      @courses = Course.all
    end 

    def show
       @section = Section.new
       @lesson = Lesson.new
    end

  private

   def require_authorized_for_current_course
    if current_course.user != current_user
      render plain: "Unauthorized", status: :unauthorized
    end
  end

  helper_method :current_course
  def current_course
    @current_course ||= Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :description, :cost)
  end 
end

app/controllers/instructor/lessons_controller.rb
class Instructor::LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_section, only: [:create]
  before_action :require_authorized_for_current_section, only: [:update]

  def create 
    @lesson = current_section.lessons.create(lesson_params)
    redirect_to instructor_course_path(current_section.course)
  end

  def update
    current_lesson.update_attributes(lesson_params)
    render plain: 'updated!'
  end

  private

    def require_authorized_for_current_lesson
      if current_lesson.section.course.user != current_user
        render plain: 'Unauthorized', status: :unauthorized
      end
    end


  def current_lesson
  @current_lesson ||= Lesson.find(params[:id])
  end

  def require_authorized_for_current_section
    if current_section.course.user != current_user
      return render plain: 'Unauthorized', status: :unauthorized 
    end
  end

  helper_method :current_section
  def current_section
    @current_section ||= Section.find(params[:section_id])
  end

  def lesson_params
    params.require(:lesson).permit(:title, :subtitle, :video, :row_order_position)
  end
end 

app/controllers/instructor/sections_controller.rb
class Instructor::SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only: [:create]
  before_action :require_authorized_for_current_course


  def create
    @section = current_course.sections.create(section_params)
    redirect_to instructor_course_path(current_course)
  end

  private

   def require_authorized_for_current_course
    if current_course.user != current_user
      render plain: "Unauthorized", status: :unauthorized
    end
  end

  helper_method :current_course
  def current_course
    @current_course ||= Course.find(params[:course_id])
  end

  def section_params
    params.require(:section).permit(:title)
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController

  def index
  end

  def privacy
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/dashboards/show.html.erb
<br />

<div class="booyah-box col-10 offset-1">
    <h1>What I'm Learning</h1>
      <% current_user.enrolled_courses.each do |course| %>
    <h3 class="text-center">
      <%= link_to course.title, course_path(course) %>
    </h3>
    <br />
     <%= image_tag course.image, class: 'img-fluid' %>
     <br />
       <div class="row">
       <div class="col-12 col-sm-8">
     <%= course.description %>
      </div>
      <div class="col-12 col-sm-4 text-center">
         <%= link_to "More Info...", course_path(course), class: 'btn btn-lg btn-primary' %>
      </div>
    <hr class="col-8 offset-2">
    <br class="clr" />
    </div>
  <% end %>
   <h1>What I'm Teaching</h1>
  <% current_user.courses.each do |course| %>
    <h3 class="text-center">
      <%= link_to course.title, course_path(course) %>
    </h3>
    <br >
    <%= image_tag course.image, class: 'img-fluid' %>
    <br />
      <div class="row">
       <div class="col-12 col-sm-8">
    <%= course.description %>
       </div>

       <div class="col-12 col-sm-4 text-center">
     <%= link_to "More Info...", course_path(course), class: 'btn btn-lg btn-primary' %>
     </div>
   </div>
   <hr class="col-8 offset-2">
   <br class="clr" />
  <% end %>
</div>

app/views/instructor/courses/index.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1 class="text-center">Learn something today</h1>
  <hr />

  <% @courses.each do |course| %>
    <h2 class="text-center">
      <%= link_to course.title, course_path(course) %>
     </h2>
    <br />
      <div class="row">
        <div class="col-sm-8 col-12">
      <%= course.description %>
    </div>
    <div class="col-sm-4 col-12 text-center">
      <%= link_to 'More Details...', course_path(course), class: 'btn btn-primary btn-large' %>
    </div>
  </div>
  <br class="clr" />
  <% end %>
</div>

app/views/instructor/courses/show.html.erb
<script>
  $(function() {
   $('.new-lesson-button').click(function( event ) {
      var lessonUrl = $(event.target).data('lesson-url');
      $('#newLessonForm').attr('action', lessonUrl);
    });

    $('.lessons').sortable({
      update: function( event, ui ) {
        $.ajax({
          type: 'PUT',
          url: ui.item.data('update-url'),
          dataType: 'json',
          data: { lesson: { row_order_position: ui.item.index() } }
        });
      }
    });


    $('.sections').sortable({
      update: function( event, ui ) {
        $.ajax({
          type: 'PUT',
          url: ui.item.data('update-url'),
          dataType: 'json',
          data: { section: { row_order_position: ui.item.index() } }
        });
      }
    });

  });
</script>

<br />
<div class="booyah-box col-10 offset-1">
  <h1 class="text-center"><%= current_course.title %></h1>
  <%= image_tag current_course.image, class: 'img-fluid' %>

  <div class="text-center">
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#newSectionModal">
      Add a new section...
    </button>
  </div>

  <ul class="sections">
    <% current_course.sections.rank(:row_order).each do |section| %>
      <li data-update-url="<%= instructor_section_path section %>" class="section-li">
        <div class="header float-left">
          <span class="fa fa-ellipsis-v"></span>
          <%= section.title %>
        </div>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary btn-lg float-right" data-toggle="modal" data-target="#newLessonModal"  data-lesson-url="<%= instructor_section_lessons_path(section) %>">
          New Lesson...
        </button>

        <br class="clr" />
        <br class="clr" />

        <ul class="lessons">
          <% section.lessons.rank(:row_order).each do |lesson| %>
            <li data-update-url="<%= instructor_lesson_path lesson %>">
              <div class="row">
                <div class="col-1">
                  <br />
                  <span class="fa fa-ellipsis-v"></span>
                </div>
                <div class="col-11 text-center">
                  <p>
                    <b><%= lesson.title %></b>
                  </p>
                  <p>
                    <%= lesson.subtitle %>
                  </p>
                </div>
              </div>
              <br class="clr" />
            </li>
          <% end %>
        </ul>
        <br class="clr" />
      </li>
    <% end %>
  </ul>
</div>


<!-- Modal -->
<div class="modal fade" id="newSectionModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="newSectionModalLabel">Add a new section</h4>
      </div>
      <%= simple_form_for @section, url: instructor_course_sections_path(current_course) do |f| %>
        <div class="modal-body">
          <%= f.input :title %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Add a section", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>






<!-- Modal -->
<div class="modal fade" id="newLessonModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="newLessonModalLabel">Add a new lesson</h4>
      </div>
      <%= simple_form_for @lesson, url: "#", html: {id: 'newLessonForm' } do |f| %>
      <form accept-charset="UTF-8" action="#" class="simple_form new_lesson" enctype="multipart/form-data" id="newLessonForm" method="post" novalidate="novalidate"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="✓" /><input name="authenticity_token" type="hidden" value="cWn+DdJbIjqZajnzD956Ox4jjPXsnn7178AzOldv0XI=" /></div>
        <div class="modal-body">
          <%= f.input :title %>
          <%= f.input :subtitle %>
          <%= f.input :video %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Add the lesson", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/instructor/lessons/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add a new lesson</h1>
  <%= simple_form_for @lesson, url: instructor_section_lessons_path(current_course) do |f| %>
  <%= f.input :title %>
  <%= f.input :subtitle %>
  <%= f.input :video %>
  <br />
  <%= f.submit "Add the lesson" %>
  <br />
  <br />
  <% end %>
</div>

app/views/instructor/sections/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add a new section</h1>
  <%= simple_form_for @section, url: instructor_course_sections_path(@course) do |f| %>
    <% f.input :title %>
    <br />
    <%= f.submit "Add a section", class: 'btn btn-primary' %>
    <br />
    <br />
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flixter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="http://vjs.zencdn.net/5.12.6/video-js.css" rel="stylesheet">
  </head>

  <body>
<div id="flex-content-container">
  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Navbar</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav> 

    <%= yield %>
  </div>

  <div id="footer">
    <div class="container">
   <div class="row">
      <div class="col-12 col-sm-3">
        <b>Teachers</b>
        <br />
        <%= link_to 'Teach a Course', new_instructor_course_path %>
        <br />
        <%= link_to 'My Dashboard', dashboard_path %>
      </div>
      <div class="col-12 col-sm-3">
        <b>About</b>
        <br />
        <%= link_to 'Team', '#' %>
        <br />
        <%= link_to 'Careers', '#' %>
        <br />
        <%= link_to 'Privacy Policy', privacy_path %>
      </div>
      <div class="col-12 col-sm-3">
        <b>Contact</b>
        <br />
        my@email.com
        <br />
        One Kendall Square
        <br />
        Cambridge MA, 02113
      </div>
      <div class="col-12 col-sm-3 social">
        <b>Social</b>
        <br />
        <br />
        <%= link_to 'http://github.com/austinwalka' do %>
        <span class="fa fa-github-square fa-2x social-button"></span>
        <% end %>
        <span class="fa fa-facebook-square fa-2x social-button"></span>
        <span class="fa fa-twitter-square fa-2x social-button"></span>
      </div>
    </div>
    </div>
  </div>

    <script src="http://vjs.zencdn.net/5.12.6/video.js"></script>
    <script src="http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
  </body>
</html>

app/views/lessons/show.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1><%= current_lesson.title %></h1>
  <p class="float-left">
    <%= current_lesson.subtitle %>
  </p>

 <% if current_lesson.next_lesson.present? %>
      <%= link_to lesson_path(current_lesson.next_lesson), class: 'btn btn-default float-right' do %>
      Next Lesson &nbsp;
      <span class="fa fa-forward"></span>
    <% end %>
  <% end %>

  <br class="clr" />
  <br />

     <video id="my-video" class="video-js vjs-big-play-centered vjs-fluid"
      poster="<%= image_path('black.jpg')" data-setup="{}">
     <source src="<%= current_lesson.video.to_s %>" type='video/mp4'>
      <noscript>
    <p class="vjs-no-js">
      To view this video please enable JavaScript, and consider upgrading to a web browser that
      <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
    </p>
    </noscript>
  </video>



</div> 

app/views/static_page/index.html.erb
<div class="hero">
  <br />
  <div class="frosty col-10 offset-1 text-center">
    <br />
    <h1>Learn Magic from the Pros</h1>
    <br />
    <h2>I'm an illusionist, Michael.</h2>
    <br />
    <%= link_to 'Learn More', courses_path, class: 'btn btn-success' %>
    <br />
  </div>
 </div> 
 <br />
 <div class="row feature text-center">
  <div class="col-12 col-sm">
    <h3>Amazing Courses</h3>
    <br />
    <p>Choose from any number of courses to study with amazing teachers.</p>
  </div>

  <div class="col-12 col-sm">
    <h3>Learn At Your Own Pace</h3>
    <br />
    <p>Enroll and access a courses archive of lessons.</p>
  </div>

  <div class="col-12 col-sm">
    <h3>Join our Community</h3>
    <br />
    <p>Learn with a community of like-minded individuals.</p>
  </div>
</div>

app/views/static_page/privacy.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1>Privacy Policy</h1>

  <p>
    We don't believe in Privacy Policies because YOLO.
  </p>
</div>